<?php // autogenerated on DATE by SurvosCrudBundle:Generator:FormType.php.twig
# /usr/sites/sf/survos-standard/src/Acme/MovieBundle/Form/Type/ActorType.php

namespace Acme\MovieBundle\Form\Type;

use Acme\MovieBundle\Form\Type\om\BaseActorType;

class ActorType extends BaseActorType
{

}

