<?php // autogenerated on DATE by SurvosCrudBundle:Generator:FormType.php.twig
# /usr/sites/sf/survos-standard/src/Acme/MovieBundle/Form/Type/ActorHasMovieType.php

namespace Acme\MovieBundle\Form\Type;

use Acme\MovieBundle\Form\Type\om\BaseActorHasMovieType;

class ActorHasMovieType extends BaseActorHasMovieType
{

}

