<?php // autogenerated on DATE by SurvosCrudBundle:Generator:Controller.php.twig
# /usr/sites/sf/survos-standard/src/Acme/MovieBundle/Controller/MovieController.php


namespace Acme\MovieBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

use Pagerfanta\Pagerfanta;
use Pagerfanta\Adapter\PropelAdapter;

use Acme\MovieBundle\Model\MovieQuery;
use Acme\MovieBundle\Model\Movie;
use Acme\MovieBundle\Form\Type\MovieType;

/**
 * @Route("/Movie")
*/
class MovieController extends Controller
{

    /**
     * @Route("/", name="acme_movie_Movie_index")
     * @Template("AcmeMovieBundle:Movie:browse.html.twig")
     */
    public function indexAction()
    {
    $query = MovieQuery::create();
		$adapter = new PropelAdapter($query);
		$request = $this->getRequest();
    $q = $request->query->get('q', '');
    if ($q) {
      $query->filterByTitle("%$q%"); // ->_or()->filterByCity("%$q%"); ??
    }
		$page = $request->query->get('page', 1);

    $pagerfanta = new Pagerfanta($adapter);
    $pagerfanta->setMaxPerPage(20); // 10 by Movie
    $pagerfanta->setCurrentPage($page);
 	  return array(
    	  	'pager' => $pagerfanta,
    	  	'Movies' => $pagerfanta->getCurrentPageResults() );
    }

    /**
     * @Route("/edit/{id}", requirements={"id" = "\d+"}, name="acme_movie_Movie_edit")
     * @Template()
     */
    function editAction(Movie $Movie) {
        $form = $this->createForm(new MovieType(), $Movie);

        $request = $this->getRequest();
        if ('POST' === $request->getMethod()) {
            $form->bindRequest($request);

            if ($form->isValid()) {
                $Movie->save();
                return $this->redirect($this->generateUrl('acme_movie_Movie_display',
                  array('id' => $Movie->getId())));
            }
        }

        return array(
            'Movie' => $Movie,
            'form' => $form->createView()
        );
    }

    /**
     * @Route("/new", name="acme_movie_Movie_new")
     * @Template()
     */
    function newAction() {
        $Movie = new Movie();
        $form = $this->createForm(new MovieType(), $Movie);

        $request = $this->getRequest();
        if ('POST' === $request->getMethod()) {
            $form->bindRequest($request);

            if ($form->isValid()) {
                $Movie->save();
                return $this->redirect($this->generateUrl('acme_movie_Movie_display',
                  array('id' => $Movie->getId())));
            }
        }

        return array(
            'form' => $form->createView()
        );
    }

    /**
     * @Route("/{id}", name="acme_movie_Movie_display")
     * @Template()
     */
    function displayAction($id)
    {
        $movie = MovieQuery::create()->findOneById($id);
        return array(
            'movie' => $movie
        );
    }

}

