<?php // autogenerated on DATE by SurvosCrudBundle:Generator:BaseFormType.php.twig
# /usr/sites/sf/survos-standard/src/Acme/MovieBundle/Form/Type/om/BaseActorType.php


namespace Acme\MovieBundle\Form\Type\om;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;

class BaseActorType extends AbstractType
{
    public function buildForm(FormBuilder $builder, array $options)
    {
                $builder->add('Id'); // INTEGER 
                $builder->add('Name'); // VARCHAR .255 
            }

    public function getDefaultOptions(array $options)
    {
        return array(
            'data_class' => 'Acme\MovieBundle\Model\Actor',
        );
    }

    public function getName()
    {
        return 'Actor'; // right name??
    }
}


