<?php // autogenerated on DATE by SurvosCrudBundle:Generator:BaseFormType.php.twig
# /usr/sites/sf/survos-standard/src/Acme/MovieBundle/Form/Type/om/BaseActorHasMovieType.php


namespace Acme\MovieBundle\Form\Type\om;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;

class BaseActorHasMovieType extends AbstractType
{
    public function buildForm(FormBuilder $builder, array $options)
    {
                $builder->add('ActorId'); // INTEGER 
                $builder->add('MovieId'); // INTEGER 
            }

    public function getDefaultOptions(array $options)
    {
        return array(
            'data_class' => 'Acme\MovieBundle\Model\ActorHasMovie',
        );
    }

    public function getName()
    {
        return 'ActorHasMovie'; // right name??
    }
}


